// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.2
// source: deliverystats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliveryWebhook is one simulated provider delivery-status callback for a
// single outbound message, across three channels (email, sms, whatsapp).
// webhook_id is what this edge's dedup keys on, not message_id: a real
// provider (SendGrid, Twilio, the WhatsApp Business API) retries a webhook
// POST on any non-2xx response or a receiver timeout, resending the
// identical webhook_id, so the dedup key here has to be the delivery
// attempt's own id. message_id is not unique in this stream by design: one
// outbound message legitimately produces more than one webhook over its
// lifecycle (sent, then delivered, then possibly bounced), and the
// dashboard's per-channel counts are counts of webhooks (delivery events),
// not counts of distinct messages.
type DeliveryWebhook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookId     string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"` // email | sms | whatsapp
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`   // sent | delivered | bounced | failed
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"` // sendgrid | twilio | meta_whatsapp (simulated)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryWebhook) Reset() {
	*x = DeliveryWebhook{}
	mi := &file_deliverystats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryWebhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryWebhook) ProtoMessage() {}

func (x *DeliveryWebhook) ProtoReflect() protoreflect.Message {
	mi := &file_deliverystats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryWebhook.ProtoReflect.Descriptor instead.
func (*DeliveryWebhook) Descriptor() ([]byte, []int) {
	return file_deliverystats_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryWebhook) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DeliveryWebhook) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryWebhook) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DeliveryWebhook) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliveryWebhook) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *DeliveryWebhook) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_deliverystats_proto protoreflect.FileDescriptor

const file_deliverystats_proto_rawDesc = "" +
	"\n" +
	"\x13deliverystats.proto\x12\rdeliverystats\"\xc0\x01\n" +
	"\x0fDeliveryWebhook\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bproviderB Z\x1edevice-telemetry-gateway/protob\x06proto3"

var (
	file_deliverystats_proto_rawDescOnce sync.Once
	file_deliverystats_proto_rawDescData []byte
)

func file_deliverystats_proto_rawDescGZIP() []byte {
	file_deliverystats_proto_rawDescOnce.Do(func() {
		file_deliverystats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deliverystats_proto_rawDesc), len(file_deliverystats_proto_rawDesc)))
	})
	return file_deliverystats_proto_rawDescData
}

var file_deliverystats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_deliverystats_proto_goTypes = []any{
	(*DeliveryWebhook)(nil), // 0: deliverystats.DeliveryWebhook
}
var file_deliverystats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deliverystats_proto_init() }
func file_deliverystats_proto_init() {
	if File_deliverystats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deliverystats_proto_rawDesc), len(file_deliverystats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deliverystats_proto_goTypes,
		DependencyIndexes: file_deliverystats_proto_depIdxs,
		MessageInfos:      file_deliverystats_proto_msgTypes,
	}.Build()
	File_deliverystats_proto = out.File
	file_deliverystats_proto_goTypes = nil
	file_deliverystats_proto_depIdxs = nil
}
