// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.2
// source: storefront.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StorefrontEvent is one simulated storefront interaction, sent as a single
// binary protobuf frame to the event edge. event_id is what this edge's
// dedup keys on (unlike telemetry.Reading's compound device_id+sequence key,
// a storefront event already carries a single globally unique id, the way a
// real event-tracking SDK assigns one client-side per event so a retried
// send is trivially identifiable). attributes carries event-type-specific
// fields (category, sku, price) as strings so the schema does not need a
// oneof per event type; the segment engine parses only the attributes a
// given segment predicate needs.
type StorefrontEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // page_view | add_to_cart | purchase | cart_abandon
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorefrontEvent) Reset() {
	*x = StorefrontEvent{}
	mi := &file_storefront_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorefrontEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorefrontEvent) ProtoMessage() {}

func (x *StorefrontEvent) ProtoReflect() protoreflect.Message {
	mi := &file_storefront_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorefrontEvent.ProtoReflect.Descriptor instead.
func (*StorefrontEvent) Descriptor() ([]byte, []int) {
	return file_storefront_proto_rawDescGZIP(), []int{0}
}

func (x *StorefrontEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StorefrontEvent) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *StorefrontEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StorefrontEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *StorefrontEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_storefront_proto protoreflect.FileDescriptor

const file_storefront_proto_rawDesc = "" +
	"\n" +
	"\x10storefront.proto\x12\n" +
	"storefront\"\x99\x02\n" +
	"\x0fStorefrontEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x12K\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2+.storefront.StorefrontEvent.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B Z\x1edevice-telemetry-gateway/protob\x06proto3"

var (
	file_storefront_proto_rawDescOnce sync.Once
	file_storefront_proto_rawDescData []byte
)

func file_storefront_proto_rawDescGZIP() []byte {
	file_storefront_proto_rawDescOnce.Do(func() {
		file_storefront_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storefront_proto_rawDesc), len(file_storefront_proto_rawDesc)))
	})
	return file_storefront_proto_rawDescData
}

var file_storefront_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storefront_proto_goTypes = []any{
	(*StorefrontEvent)(nil), // 0: storefront.StorefrontEvent
	nil,                     // 1: storefront.StorefrontEvent.AttributesEntry
}
var file_storefront_proto_depIdxs = []int32{
	1, // 0: storefront.StorefrontEvent.attributes:type_name -> storefront.StorefrontEvent.AttributesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storefront_proto_init() }
func file_storefront_proto_init() {
	if File_storefront_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storefront_proto_rawDesc), len(file_storefront_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storefront_proto_goTypes,
		DependencyIndexes: file_storefront_proto_depIdxs,
		MessageInfos:      file_storefront_proto_msgTypes,
	}.Build()
	File_storefront_proto = out.File
	file_storefront_proto_goTypes = nil
	file_storefront_proto_depIdxs = nil
}
